function ContentCard({
  title,
  platform,
  content,
  hashtags,
  generatedTime,
  children,
}) {
  return (
    <div className="bg-white/10 backdrop-blur-lg rounded-2xl p-6 shadow-lg border border-white/20 hover:shadow-2xl hover:-translate-y-1 transition-all duration-300">

      {/* Title */}
      <h2 className="text-2xl font-bold text-white mb-2">
        {title}
      </h2>
      <div className="inline-block bg-purple-600 text-white text-xs px-3 py-1 rounded-full mb-3">
            ✨ Generated by LaunchPad AI
      </div>

      {/* Platform */}
      {platform && (
        <p className="text-purple-300 font-semibold mb-2">
          📱 {platform}
        </p>
      )}

      {/* Content */}
      <p className="text-gray-200 leading-7 whitespace-pre-line">
        {content}
      </p>

      {/* Hashtags */}
      {hashtags && (
        <p className="text-blue-300 mt-4">
          {hashtags}
        </p>
      )}

      {/* Generated Time */}
      {generatedTime && (
        <p className="text-gray-400 text-sm mt-4">
          ✨ Generated {generatedTime}
        </p>
      )}

      {/* Buttons will appear here */}
      <div className="mt-6 flex flex-wrap gap-3">
        {children}
      </div>

    </div>
  );
}

export default ContentCard;